### ISSUE TITLE
YT

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/Homepage#1]
can I have your YT channel link

**Comment by JBYT27** [comment]
waittt why? lmao

**Comment by darkdarcool** [comment]
BECAUSE, YOU SAID YOU HAVE ONE

**Comment by JBYT27** [comment]
oh. lmao sure. i just have to get link...

> I'll get back to you tmrw ;)

**Comment by darkdarcool** [comment]
OKIE

**Comment by darkdarcool** [comment]
FAST COMMENT RIGHT

**Comment by darkdarcool** [comment]
EEEEEEEEEEEEE

**Comment by darkdarcool** [comment]
can I get it now?

**Comment by JBYT27** [comment]
lol, sorry for late reply, and bc it kinda is a personal yt channel, afraid i cant share it, ill let you know with new channel.

Sorry again! :(

**Comment by darkdarcool** [comment]
Oh ok, so  guessing your voice and name is on there. Ok, that’s fine. But how many subs do you have?

**Comment by JBYT27** [comment]
around 15 lmao

**Comment by darkdarcool** [comment]
Lol how many are your family?

**Comment by JBYT27** [comment]
prob like 2-3 xD

**Comment by darkdarcool** [comment]
Knew it

**Comment by JBYT27** [comment]
xD lmao

**Comment by darkdarcool** [comment]
e

**Comment by iop3** [comment]
(im late in this conversation >:| ) what do you do in ur yt channel? ~~(i have no idea why im asking i cant even watch yt lmfao)~~

**Comment by iop3** [comment]
im pretty sure i have to ping you or else you wont get any notif cuz this issue is closed... @JBYT27

**Comment by JBYT27** [comment]
lol, uh, basically i do gaming and music. (lol that sucks xD)

**Comment by darkdarcool** [comment]
What games?

**Comment by JBYT27** [comment]
Mostly Overwatch, planning to do Genshin Impact

**Comment by darkdarcool** [comment]
lol ok

**Comment by JBYT27** [comment]
:)

**Comment by darkdarcool** [comment]
For some reason I have a thing against Genshin for taking too much inspiration from Breath of the Wild, which is one of my favorite games(HYPED FOR THE SEQUAL)

**Comment by JBYT27** [comment]
lol ok

**Comment by iop3** [comment]
~~(oh quiznack why didn't i see you guys responding...prob this issue is closed :/)~~ ok thanks @JBYT27. lol @darkdarcool

**Comment by darkdarcool** [comment]
lol ok
