### ISSUE TITLE
Chore: make dark/light mode

### ISSUE THREAD

**Issue by JBYT27** [JBYT27/Homepage#2]
Make dark and light mode button.

**Comment by JBYT27** [comment]
If you can help, please comment or leave a PR. 

Thanks!

**Comment by iop3** [comment]
well... just copy Repl-it-Coders? --> https://github.com/Repl-it-Coders/About-Page/blob/main/views/index.html

just put the code (about the switch theme ig?) in ur code. bam done

**Comment by JBYT27** [comment]
lol xD thanks :D

**Comment by iop3** [comment]
wait did that actually work?

**Comment by JBYT27** [comment]
i didnt try yet, but i will soon lol

**Comment by iop3** [comment]
lol ok!

**Comment by iop3** [comment]
:)

**Comment by JBYT27** [comment]
Closing

**Comment by iop3** [comment]
ok sure
